package ut.ee.xtorrent.tracker;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import ut.ee.xtorrent.common.Peer;
import ut.ee.xtorrent.common.TrackerResponse;

import java.util.ArrayList;
import java.util.List;

@RestController
@RequestMapping("/tracker")
public class TrackerController {

    private static final String TRACKER_ID = "1";
    private static final int DEFAULT_INTERVAL = 60;

    /**
     * @param infoHash   urlencoded 20-byte SHA1 hash of the value of the info key from the Metainfo file.
     * @param peerId     urlencoded 20-byte string used as a unique ID for the client, generated by the client at startup.
     * @param port       The port number that the client is listening on.
     * @param uploaded   The total amount uploaded (since the client sent the 'started' event to the tracker) in base ten ASCII.
     * @param downloaded The total amount downloaded (since the client sent the 'started' event to the tracker) in base ten ASCII.
     * @param left       The number of bytes this client still has to download in base ten ASCII.
     * @param compact    Setting this to 1 indicates that the client accepts a compact response.
     * @param noPeerId   Indicates that the tracker can omit peer id field in peers dictionary. This option is ignored if compact is enabled.
     * @param eventName  (Optional) If specified, must be one of started, completed, stopped. If not specified, then this request is one performed at regular intervals.
     * @param ip         (Optional) The true IP address of the client machine, in dotted quad format or rfc3513 defined hexed IPv6 address.
     * @param numwant    (Optional) Number of peers that the client would like to receive from the tracker.
     * @param key        (Optional) An additional identification that is not shared with any other peers.
     * @param trackerId  (Optional) If a previous announce contained a tracker id, it should be set here.
     * @return
     */
    @RequestMapping("/announce")
    public TrackerResponse announce(
            @RequestParam(value = "info_hash") String infoHash,
            @RequestParam(value = "peer_id") String peerId,
            @RequestParam(value = "port") int port,
            @RequestParam(value = "uploaded") String uploaded,
            @RequestParam(value = "downloaded") String downloaded,
            @RequestParam(value = "left") String left,
            @RequestParam(value = "compact", defaultValue = "false") boolean compact,
            @RequestParam(value = "no_peer_id") String noPeerId,
            @RequestParam(value = "event", required = false) String eventName,
            @RequestParam(value = "ip", required = false) String ip,
            @RequestParam(value = "numwant", required = false) String numwant,
            @RequestParam(value = "key", required = false) String key,
            @RequestParam(value = "tracker_id", required = false) String trackerId
    ) {
        if (eventName != null) {
            Event event = Event.getEvent(eventName);
        }

        // number of peers with the entire file (seeders)
        int complete = 0;

        // number of non-seeder peers (leechers)
        int incomplete = 0;

        List<Peer> peers = new ArrayList<>();

        return TrackerResponse.builder()
                .setInterval(DEFAULT_INTERVAL)
                .setTrackerId(TRACKER_ID)
                .setComplete(complete)
                .setIncomplete(incomplete)
                .setPeers(peers)
                .build();
    }

}
